# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrant boxes are usually 8 GB, so we create a separate disk to hold
# work files, cf https://gist.github.com/leifg/4713995. This also the
# file we can share to speed up setup.
# Reference on https://github.com/the-virtual-brain/tvb-recon/blob/master/Vagrantfile

$script = <<-SCRIPT
#!/bin/bash

echo "Installing The Virtual Brain Packages on virtual machine..."

# Get Miniconda and make it the main Python interpreter
ENV LANG=C.UTF-8 LC_ALL=C.UTF-8
ENV PATH /opt/conda/bin:$PATH

apt-get update --fix-missing && apt-get install -y wget bzip2 ca-certificates \
    libglib2.0-0 libxext6 libsm6 libxrender1 \
    git mercurial subversion

wget --quiet https://repo.anaconda.com/miniconda/Miniconda2-4.5.4-Linux-x86_64.sh -O ~/miniconda.sh && \
    /bin/bash ~/miniconda.sh -b -p /opt/conda && \
    rm ~/miniconda.sh && \
    ln -s /opt/conda/etc/profile.d/conda.sh /etc/profile.d/conda.sh && \
    echo ". /opt/conda/etc/profile.d/conda.sh" >> ~/.bashrc && \
    echo "conda activate base" >> ~/.bashrc

apt-get install -y curl grep sed dpkg && \
    TINI_VERSION=`curl https://github.com/krallin/tini/releases/latest | grep -o "/v.*\"" | sed 's:^..\(.*\).$:\1:'` && \
    curl -L "https://github.com/krallin/tini/releases/download/v${TINI_VERSION}/tini_${TINI_VERSION}.deb" > tini.deb && \
    dpkg -i tini.deb && \
    rm tini.deb && \
    apt-get clean
# Install the remaining 3rd tools using pypi
pip install jaraco.functools allensdk

echo "Installing TVB packages using conda"
conda config --add channels conda-forge
conda install tvb-framework -y

# End the installation
echo "Finished Installing TVB Packages."

echo "Starting the framwork"
python -m tvb.interfaces.web.run WEB_PROFILE tvb.config
SCRIPT

work_disk = 'tvb_distribution.vdi'

Vagrant.configure("2") do |config|

    # Box
    config.vm.box = "debian/stretch64"

    # Shared folders
    #config.vm.synced_folder ".", "/opt"
	
    # Set port forwarded_port 
    config.vm.network :forwarded_port, guest: 8080, host: 8080, auto_correct: true
	
    # Set virtualbox as a provider and customize 6GB as Ram.
    config.vm.provider "virtualbox" do |vb|
      vb.cpus = 2
      vb.memory = "6144"
      unless File.exist?(work_disk)
        size_in_mb = 50 * 1024
        vb.customize ['createhd', '--filename', work_disk, '--size', size_in_mb]
      end
      vb.customize ['storageattach', :id, '--storagectl', 'SCSI', '--port', 4, '--device', 0, '--type', 'hdd', '--medium', work_disk]
    end
	
    # Download tvb packages and Start it.
	config.vm.provision "shell", inline: $script

end
